### ISSUE TITLE
Throws NullPointerException

### ISSUE THREAD

**Issue by SchneeziMichi** [felsenhower/stine_calendar_bot#8]
Tried using it, got output:
(Didn't use language option and used -pass=--)

Lade STiNE-Hauptseite...
Anmelden...
Setze Sprache auf Deutsch...
Bereite Download vor...
java.lang.NullPointerException
	at io.github.felsenhower.stine_calendar_bot.util.Browser.getByXPath(Browser.java:148)
	at io.github.felsenhower.stine_calendar_bot.calendars.CalendarDataDownloader.<init>(CalendarDataDownloader.java:78)
	at io.github.felsenhower.stine_calendar_bot.calendars.CalendarProcessor.<init>(CalendarProcessor.java:39)
	at io.github.felsenhower.stine_calendar_bot.main.Main.<init>(Main.java:52)
	at io.github.felsenhower.stine_calendar_bot.main.Main.main(Main.java:26)

**Comment by felsenhower** [comment]
Context:
- [Browser.java:L148](https://github.com/felsenhower/stine_calendar_bot/blob/daecadf41b3ad49969ec386cadde860638df57e0/src/main/java/io/github/felsenhower/stine_calendar_bot/util/Browser.java#L148)
- [CalendarDataDownloader.java:78](https://github.com/felsenhower/stine_calendar_bot/blob/daecadf41b3ad49969ec386cadde860638df57e0/src/main/java/io/github/felsenhower/stine_calendar_bot/calendars/CalendarDataDownloader.java#L78)
- [CalendarProcessor.java:39](https://github.com/felsenhower/stine_calendar_bot/blob/daecadf41b3ad49969ec386cadde860638df57e0/src/main/java/io/github/felsenhower/stine_calendar_bot/calendars/CalendarProcessor.java#L39)

**Comment by felsenhower** [comment]
Uncaught Exception, but STiNE was probably just down, so probably won't fix in the next time.
